local_repository(
    name = "rules_uniffi",
    path = "../..",
)

load("@rules_uniffi//uniffi:repositories.bzl", "rules_uniffi_dependencies")

rules_uniffi_dependencies()

load("@rules_uniffi//uniffi:setup.bzl", "rules_uniffi_setup")

rules_uniffi_setup()

register_toolchains("//:kotlin_toolchain")
